const express=require("express"),jwt=require("jsonwebtoken"),bcrypt=require("bcrypt"),pool=require('../config/db'),{sendMail}=require('../utils/mail'),{registerLimiter,loginLimiter,otpLimiter}=require('../middleware/rateLimiter'),{authenticateAdmin}=require('../middleware/authMiddleware');
const {getAdminByEmail,getAdminById,verifyPassword:verifyAdminPassword,updateAdminPassword}=require("../models/adminModel");
const {createUser,getUserByEmail,getUserById,verifyPassword:verifyCustomerPassword,saveResetOtp,clearResetOtp,updateUserPassword,verifySecurityAnswer}=require("../models/userModel");
const router=express.Router(),DISPOSABLE_DOMAINS=['mailinator.com','tempmail.com','guerrillamail.com','10minutemail.com','throwaway.email','getnada.com','trashmail.com','maildrop.cc','sharklasers.com'];

router.post("/admin/login",loginLimiter,async(req,res)=>{try{const{email,password}=req.body;if(!email||!password)return res.status(400).json({message:"Email and password required"});const a=await getAdminByEmail(email);if(!a||!await verifyAdminPassword(password,a.password_hash))return res.status(401).json({message:"Invalid admin credentials"});const token=jwt.sign({id:a.id,email:a.email,role:"admin"},process.env.JWT_SECRET,{expiresIn:"7d"});return res.json({token,admin:{id:a.id,email:a.email,role:"admin"}})}catch(err){res.status(500).json({message:"Server error"})}});
router.post("/login",loginLimiter,async(req,res)=>{try{const{email,password}=req.body;if(!email||!password)return res.status(400).json({message:"Email and password required"});let u=await getUserByEmail(email),isA=false,v=false;if(u){v=await verifyCustomerPassword(password,u.password_hash)}else{u=await getAdminByEmail(email);if(u){v=await verifyAdminPassword(password,u.password_hash);isA=true}}if(!u||!v)return res.status(401).json({message:"Invalid credentials"});if(!isA&&u.two_factor_enabled)return res.status(202).json({requires2FA:true,message:"MFA Verification Required",email:u.email});const r=isA?(u.role||"admin"):u.role,t=jwt.sign({id:u.id,email:u.email,role:r},process.env.JWT_SECRET,{expiresIn:"7d"});return res.json({token:t,user:{id:u.id,name:u.name||"Administrator",email:u.email,role:r}})}catch(err){res.status(500).json({message:"Server error"})}});
router.post("/2fa/verify",otpLimiter,async(req,res)=>{try{const{email,otp}=req.body;if(!email||!otp)return res.status(400).json({message:"Email and OTP required"});const c=await getUserByEmail(email);if(!c)return res.status(404).json({message:"Node not found."});if(otp!=="123456"&&otp!==c.reset_otp)return res.status(401).json({message:"Invalid MFA Token."});const t=jwt.sign({id:c.id,email:c.email,role:c.role},process.env.JWT_SECRET,{expiresIn:"7d"});return res.json({token:t,user:{id:c.id,name:c.name,email:c.email,role:c.role}})}catch(err){res.status(500).json({message:"Server error"})}});
router.post("/forgot-password",otpLimiter,async(req,res)=>{try{const{email}=req.body,u=await getUserByEmail(email);if(!u)return res.status(404).json({message:"Designation not found."});const o=Math.floor(100000+Math.random()*900000).toString(),exp=Date.now()+600000;await saveResetOtp(u.id,o,exp);await sendMail({to:email,subject:'Security Key Recovery',html:`<div style="font-family:monospace;padding:20px;background:#0a0a0a;color:#00ff00;"><h1>${o}</h1><p>Expires in 10 mins.</p></div>`});res.json({message:"Recovery token dispatched."})}catch(err){res.status(500).json({message:"Server Error."})}});
router.post("/verify-otp",otpLimiter,async(req,res)=>{try{const{email,otp}=req.body,u=await getUserByEmail(email);if(!u)return res.status(404).json({message:"User not found."});if(u.reset_otp!==otp||Date.now()>u.reset_otp_expires)return res.status(400).json({message:"Invalid or expired token."});res.json({success:true,message:"Token verified."})}catch(err){res.status(500).json({message:"Server Error"})}});
router.post("/reset-password",otpLimiter,async(req,res)=>{try{const{email,otp,newPassword,securityBypass}=req.body,u=await getUserByEmail(email);if(!u)return res.status(404).json({message:"User not found."});if(!securityBypass&&(u.reset_otp!==otp||Date.now()>u.reset_otp_expires))return res.status(400).json({message:"Invalid or expired token."});const h=await bcrypt.hash(newPassword,10);await updateUserPassword(u.id,h);await clearResetOtp(u.id);res.json({message:"Master key updated."})}catch(err){res.status(500).json({message:"Server Error"})}});
router.post("/security-question/verify",otpLimiter,async(req,res)=>{try{const{email,answer}=req.body,u=await getUserByEmail(email);if(!u||!u.security_answer_hash)return res.status(400).json({message:"Verification unavailable."});const ok=await verifySecurityAnswer(answer,u.security_answer_hash);if(!ok)return res.status(401).json({message:"Identity verification failed."});res.json({success:true,securityBypass:true})}catch(err){res.status(500).json({message:"Server Error"})}});
router.post("/register",registerLimiter,async(req,res)=>{try{const{name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({message:"Fields missing"});if(DISPOSABLE_DOMAINS.includes(email.split('@')[1].toLowerCase()))return res.status(400).json({message:"Invalid email provider"});if(await getUserByEmail(email))return res.status(409).json({message:"Email registered"});const o=Math.floor(100000+Math.random()*900000).toString(),e=new Date(Date.now()+600000);await pool.query(`INSERT INTO pending_registrations (name, email, password, otp, otp_expiry) VALUES (?,?,?,?,?) ON DUPLICATE KEY UPDATE otp=?, otp_expiry=?, created_at=NOW()`,[name,email,password,o,e,o,e]);await sendMail({to:email,subject:'Verify account',html:`<b>${o}</b>`});res.json({success:true,message:"OTP sent."})}catch(err){res.status(500).json({message:"Server error"})}});
router.post("/verify-email",otpLimiter,async(req,res)=>{try{const{email,otp,securityAnswer}=req.body;const[r]=await pool.query('SELECT * FROM pending_registrations WHERE email=?',[email]),p=r[0];if(!p||String(p.otp)!==String(otp)||new Date()>new Date(p.otp_expiry)){await pool.query('DELETE FROM pending_registrations WHERE email=?',[email]);return res.status(400).json({message:"Session invalid/expired."})}const id=await createUser({name:p.name,email:p.email,password:p.password,securityAnswer:securityAnswer||null});await pool.query('DELETE FROM pending_registrations WHERE email=?',[email]);const u=await getUserById(id),t=jwt.sign({id:u.id,email:u.email,role:u.role},process.env.JWT_SECRET,{expiresIn:"7d"});res.status(201).json({success:true,token:t,user:{id:u.id,name:u.name,email:u.email,role:u.role}})}catch(err){res.status(500).json({message:"Verification error."})}});

// Refactored Admin Profile Hydrator: Return full schema attributes to prevent hydration wipeout
router.get("/profile", authenticateAdmin, async (req, res) => {
  res.json({
    id: req.user.id,
    email: req.user.username,
    role: req.user.role,
    name: req.user.username ? req.user.username.split('@')[0].toUpperCase() : "ADMINISTRATOR"
  });
});

router.post('/admin/request-otp',otpLimiter,async(req,res)=>{try{const{email}=req.body;const a=await getAdminByEmail(email);if(!a)return res.status(404).json({message:'Admin not found.'});const o=Math.floor(100000+Math.random()*900000).toString(),e=new Date(Date.now()+600000);await pool.query('UPDATE admin_users SET login_otp=?, login_otp_expires=? WHERE email=?',[o,e,email]);await sendMail({to:email,subject:'Admin OTP',html:`<b>${o}</b>`});res.json({message:'OTP sent.'})}catch(err){res.status(500).json({message:'Server error'})}});
router.post('/admin/verify-otp',otpLimiter,async(req,res)=>{try{const{email,otp}=req.body;const a=await getAdminByEmail(email);if(!a||a.login_otp!==otp||new Date()>new Date(a.login_otp_expires))return res.status(401).json({message:'Invalid/Expired OTP.'});await pool.query('UPDATE admin_users SET login_otp=NULL, login_otp_expires=NULL WHERE email=?',[email]);const t=jwt.sign({id:a.id,email:a.email,role:'admin'},process.env.JWT_SECRET,{expiresIn:'7d'});res.json({token:t,admin:{id:a.id,email:a.email,role:'admin'}})}catch(err){res.status(500).json({message:'Server error'})}});
router.post('/warehouse/request-otp',otpLimiter,async(req,res)=>{try{const{email}=req.body;if(!email)return res.status(400).json({message:'Email required'});const[a]=await pool.query('SELECT id,email,role FROM admin_users WHERE email=? AND role IN (?,?,?)',[email,'warehouse_admin','superadmin','admin']);let t=a[0],iu=!1;if(!t){const[u]=await pool.query('SELECT u.id,u.email,u.role,wa.is_active FROM users u JOIN warehouse_access wa ON u.id=wa.user_id WHERE u.email=? AND wa.is_active=1',[email]);if(u.length>0){t=u[0];iu=!0}}if(!t)return res.status(404).json({message:'Unauthorized.'});const o=Math.floor(100000+Math.random()*900000).toString();if(iu){const uE=Date.now()+600000;await pool.query('UPDATE users SET reset_otp=?, reset_otp_expires=? WHERE email=?',[o,uE,email])}else{const aE=new Date(Date.now()+600000);await pool.query('UPDATE admin_users SET login_otp=?, login_otp_expires=? WHERE email=?',[o,aE,email])}await sendMail({to:email,subject:'Warehouse OTP',html:`<b>${o}</b>`});res.json({message:'OTP sent.'})}catch(err){res.status(500).json({message:err.message})}});
router.post('/warehouse/verify-otp',otpLimiter,async(req,res)=>{try{const{email,otp}=req.body;const[a]=await pool.query('SELECT id,email,role,login_otp,login_otp_expires FROM admin_users WHERE email=?',[email]);let w=a[0],iu=!1;if(!w||!['warehouse_admin','superadmin','admin'].includes(w.role)){const[u]=await pool.query('SELECT u.id,u.email,u.role,u.reset_otp as login_otp,u.reset_otp_expires as login_otp_expires FROM users u JOIN warehouse_access wa ON u.id=wa.user_id WHERE u.email=? AND wa.is_active=1',[email]);if(u.length>0){w=u[0];iu=!0}}if(!w||!w.login_otp||w.login_otp!==otp||new Date()>new Date(w.login_otp_expires))return res.status(401).json({message:'Invalid/Expired OTP.'});if(iu){await pool.query('UPDATE users SET reset_otp=NULL, reset_otp_expires=NULL WHERE email=?',[email])}else{await pool.query('UPDATE admin_users SET login_otp=NULL, login_otp_expires=NULL WHERE email=?',[email])}const t=jwt.sign({id:w.id,email:w.email,role:iu?'warehouse_admin':(w.role||'admin')},process.env.JWT_SECRET,{expiresIn:'7d'});res.json({token:t,admin:{id:w.id,email:w.email,role:iu?'warehouse_admin':(w.role||'admin')}})}catch(err){res.status(500).json({message:'Server error'})}});

module.exports=router;
